# Generated by Django 4.1.2 on 2022-10-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_rename_merek_kategori_remove_produk_merek_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Merek',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='kategori',
            new_name='merek',
        ),
    ]
